apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

managedNodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2